name: myfin_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.2.0
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  http: ^1.2.1
  intl: ^0.20.2
  supabase_flutter: ^2.15.2
  flutter_secure_storage: ^10.3.1
  local_auth: ^3.0.1
  flutter_dotenv: ^6.0.1
  gpt_markdown: ^1.1.7
  pdf: ^3.12.0
  excel: ^4.0.6
  share_plus: ^13.2.1
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.0.1
  firebase_admin_sdk: ^0.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
