// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZo8txwJMPFFBW5MU8_UwVeDmPs0lupE',
    appId: '1:484409599277:web:c6d6d8b8c39ca245fcdfa4',
    messagingSenderId: '484409599277',
    projectId: 'myfin-mobile-2026',
    authDomain: 'myfin-mobile-2026.firebaseapp.com',
    storageBucket: 'myfin-mobile-2026.firebasestorage.app',
    measurementId: 'G-RKJ2ZCH7YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgEX8FYNVT6mCqjFXS0PkIS9DodowE1Mg',
    appId: '1:484409599277:android:1ddbbe56076aa7d7fcdfa4',
    messagingSenderId: '484409599277',
    projectId: 'myfin-mobile-2026',
    storageBucket: 'myfin-mobile-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmq6Dzky0919mgcc6YINPuJgaONEWsu4M',
    appId: '1:484409599277:ios:69a9ed5d6c792905fcdfa4',
    messagingSenderId: '484409599277',
    projectId: 'myfin-mobile-2026',
    storageBucket: 'myfin-mobile-2026.firebasestorage.app',
    iosClientId: '484409599277-avin416qou9bc4lhd5pb77iuqi5oip7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfinMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmq6Dzky0919mgcc6YINPuJgaONEWsu4M',
    appId: '1:484409599277:ios:69a9ed5d6c792905fcdfa4',
    messagingSenderId: '484409599277',
    projectId: 'myfin-mobile-2026',
    storageBucket: 'myfin-mobile-2026.firebasestorage.app',
    iosClientId: '484409599277-avin416qou9bc4lhd5pb77iuqi5oip7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfinMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZo8txwJMPFFBW5MU8_UwVeDmPs0lupE',
    appId: '1:484409599277:web:6b27b1bde9e6a089fcdfa4',
    messagingSenderId: '484409599277',
    projectId: 'myfin-mobile-2026',
    authDomain: 'myfin-mobile-2026.firebaseapp.com',
    storageBucket: 'myfin-mobile-2026.firebasestorage.app',
    measurementId: 'G-KZXCFTKC7V',
  );
}
